#spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#
#spring.datasource.url=jdbc:sqlite:bike.db
#spring.datasource.username=
#spring.datasource.password=
#spring.datasource.driver-class-name=org.sqlite.JDBC


security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8081/auth/user
spring:
  application:
    name: bike
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bike_local?useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: true
hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  query:
    in_clause_parameter_padding: true
server:
  port: 8080
