#Setting the logging levels for the service
logging:
  level:
    org.springframework.web: INFO
    com.sq.ch: DEBUG


server:
  contextPath:   /auth
  port: 8081

#spring:
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bike_local?useSSL=false
#    username: root
#    password: root
#  jpa:
#    generate-ddl: true
#    database: mysql
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#      hibernate.generate_statistics: true
#hibernate:
#  dialect: org.hibernate.dialect.MySQLDialect
#  query:
#    in_clause_parameter_padding: true

